name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag teleshell:beta
    - name: Check the Docker images
      run: docker images
    - name: Run the Docker image
      run: docker run teleshell:beta
